### ISSUE TITLE
Layout Shift in Profile Page

### ISSUE THREAD

**Issue by Tanmoy741127** [PalisadoesFoundation/talawa#1372]
**Describe the bug**
In the profile screen of app, the layout shift can be seen, their is not symmetric spacing between different component. You can see the "Donate us" button in attached screenshot. Also there is issue of layout overflow.

**To Reproduce**
1. Go to `Profile` screen of app
2. Check the layout

**Expected behavior**
The spacing between elements should be symmetric. And there is should not be any layout shuft.

**Actual behavior**
The expected behaviour is discussed above. Currently the page is not responsive and layout shift happening.

**Screenshots**
<img src="https://user-images.githubusercontent.com/57363826/206973111-590568e2-b65e-424f-af9d-2feca86360c9.png" width="250px"/>

**Comment by Tanmoy741127** [comment]
@palisadoes can you assign this issue

**Comment by SiddheshKukade** [comment]
@Tanmoy741127 I don't have this problem on my side.

**Comment by Tanmoy741127** [comment]
In little bit smaller screen the line gets single line to double line .
So the issue is happening.

See the "My Tasks" section,  it taking 2 lines to fit in screen.

**Comment by Tanmoy741127** [comment]
@SiddheshKukade what do you think about the issue?

**Comment by Tanmoy741127** [comment]
@palisadoes can you verify the issue of responsiveness for little bit smaller screen devices

**Comment by palisadoes** [comment]
@Tanmoy741127 What specific phone are you using in Android studio to verify this? Does it make sense fixing this for a model that doesn't exist?

**Comment by palisadoes** [comment]
Please go ahead

**Comment by Tanmoy741127** [comment]
@palisadoes the issue has been fixed in PR #1376 . Kindly review

**Comment by palisadoes** [comment]
Please remember to get your issues approved and assigned to you before submitting your PR

**Comment by palisadoes** [comment]
This issue is being reopened as the reporter bug is still present. The Pull Request was closed by the submitter without him providing a rationale.

**Comment by antonio-pedro99** [comment]
@palisadoes is there someone working on this?

**Comment by HARSH-17177** [comment]
> This issue is being reopened as the reporter bug is still present. The Pull Request was closed by the submitter without him providing a rationale.

@palisadoes please assign this to mee  i can solve this.

**Comment by palisadoes** [comment]
I'm going to close this issue. We need to focus on tests and the breaking bugs that we discovered here:  https://www.youtube.com/watch?v=ix3eSReJj2k
