### ISSUE TITLE
Bug Report: App fails to build and crash loop on startup

### ISSUE THREAD

**Issue by DevAnuragT** [PalisadoesFoundation/talawa#3054]
**Description**

There are three critical issues preventing the mobile app from running on a fresh setup:
1.  **Gradle Build Error:** The `android/app/build.gradle` throws a `GradleException` because it checks for `flutter.sdk` property which might not be defined in `local.properties` in some environments, instead of handling it gracefully.
2.  **LateInitializationError:** The `GraphqlConfig` service is accessed in `MenuPage` before it is fully initialized, causing a crash if the `Hive` box is empty (fresh install).
3.  **Splash Screen Loop:** The `SplashScreen` widget calls `sizeConfig.init(context)` inside `didChangeDependencies`, which triggers a rebuild loop, causing the splash screen to flicker or hang indefinitely.

**To Reproduce**

1.  Clone the repository.
2.  Run `flutter pub get`.
3.  Run `flutter run`.
4.  Observe `GradleException` regarding Flutter SDK.
5.  (After fixing Gradle) Run the app on a fresh emulator/device.
6.  Observe `LateInitializationError` in logs or infinite Splash Screen loop.

**Expected behavior**
The application should build successfully and launch to the Language Selection screen without crashing or looping.

**Actual behavior**
- Build fails with `GradleException`.
- App crashes with `LateInitializationError: Field 'httpLink' has not been initialized`.
- App gets stuck in an infinite loop on the Splash Screen.

**Additional details**
- **OS:** Linux (Ubuntu)
- **Fix:** I have created a PR `fix/setup-and-initialization` that resolves these issues by adding a fallback for `API_URL`, fixing the Gradle check, and moving the `sizeConfig` initialization.

**Comment by palisadoes** [comment]
1. Are you running on the `develop` or the `main` branch?
2. It should be fixed on `develop`

**Comment by DevAnuragT** [comment]
Yeah, thanks for pointing it out. I verified that the Gradle and Splash Screen fixes are already on develop. However, the LateInitializationError in main.dart is still present. I've will updated the PR to ONLY include that specific fix.

**Comment by palisadoes** [comment]
1. We will be updating main later in the month.
2. I'll close this
