### ISSUE TITLE
Proper State Management (Removal of pull to refresh )

### ISSUE THREAD

**Issue by ishan0805** [PalisadoesFoundation/talawa#334]
### Description
 I think **pull to refresh** can be avoided by proper state management . As of now manually a request is made again and again to fetch data when page is reloaded .

### Solution
Inside preference provider we can define a function that return the list of post  with a  'listener()' so that whenever a new post is created that is displayed automatically without explicitly pulling the page to refresh . 
                                                                                  OR
It can also be solved by using Streams , using BehaviorSubject Observable provided by Redux , witch is a better way of doing it as it sends the very last event that was emitted to the listener that just subscribed but  as the app is build mostly  with provider it will not match the MVVM design .

### Benefits

1. By following this approach multiple calling of `setstate()` can be avoided . As the number of news increase it will be more optimal .
2.  As list of news will be provided by preference Provided , it will be globally available for every widget below root.
3. It will remove the logic part from the UI part hence improve testing and become more readable  . 

   

![Screenshot_2021-03-15-22-50-47-684_com example talawa](https://user-images.githubusercontent.com/57336738/111212937-41f5aa00-85f6-11eb-9b6e-85c69d3d11e9.jpg)

**Comment by yasharth291** [comment]
Hello @ishan0805  actually i think you are not working on the recent code because the thing i can see on the screenshot is old and can create problem with my merge please see mentors

**Comment by yasharth291** [comment]
And i think it is resolved in the current code base

**Comment by ishan0805** [comment]
ok I will check that , thanks for the information .

**Comment by ishan0805** [comment]
@yasharth291  only the **pull to remove** text is removed  the functionally is still the same . Now user need to pull himself without knowing if its news is posted or not

**Comment by Sagar2366** [comment]
@ishan0805 you can start working on this issue. Consider this case also while working on this issue - https://github.com/PalisadoesFoundation/talawa/issues/300

**Comment by Sagar2366** [comment]
@piyushpradhan as discussed in slack channel please start working on this issue.

**Comment by piyushpradhan** [comment]
Yes, I'm on it.

**Comment by Sagar2366** [comment]
@piyushpradhan because of no activity on this issue, we will have to un-assign this issue and let someone else work on it.

**Comment by StrangeNoob** [comment]
@Sagar2366 I am working on it with @piyushpradhan. Can you assign this to me ?

**Comment by Sagar2366** [comment]
> @Sagar2366 I am working on it with @piyushpradhan. Can you assign this to me ?

@StrangeNoob any progress on this issue ?
Can you please raise PR and add issue number to it.

@ishan0805 wait for some time, do not start working on this issue.

**Comment by StrangeNoob** [comment]
@Sagar2366  I started working on it yesterday. I will let you know by tomorrow. Is it Okay?

**Comment by Sagar2366** [comment]
@StrangeNoob did we discussed about you would be working on this issue in slack ?
If yes raise PR With whatever work is done.

**Comment by StrangeNoob** [comment]
closes #334 via #518

**Comment by CyberWake** [comment]
@ishan0805 we have implemented the mvvm in the application and we are further optimising the code base this issue will be resolved uder #850 . may we close this issue?

**Comment by CyberWake** [comment]
@palisadoes sir we can close this issue as #850 will handle this one and resolve the same.
